-- 20240210_financial_engineering.sql

-- 1. Patient Wallet (Saldo a Favor)
ALTER TABLE public.patients 
ADD COLUMN IF NOT EXISTS wallet_balance DECIMAL(10, 2) DEFAULT 0 NOT NULL;

-- 2. Wallet Transactions (Log of manual top-ups or usage)
CREATE TABLE IF NOT EXISTS public.wallet_transactions (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    patient_id UUID REFERENCES public.patients(id) NOT NULL,
    amount DECIMAL(10, 2) NOT NULL, -- Positive for deposit, Negative for usage
    description TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    created_by UUID REFERENCES auth.users(id),
    clinic_id UUID REFERENCES public.clinics(id)
);

-- Trigger to update patient balance on transaction
CREATE OR REPLACE FUNCTION update_wallet_balance()
RETURNS TRIGGER AS $$
BEGIN
    UPDATE patients 
    SET wallet_balance = wallet_balance + NEW.amount
    WHERE id = NEW.patient_id;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS update_wallet_balance_trigger ON wallet_transactions;
CREATE TRIGGER update_wallet_balance_trigger
AFTER INSERT ON wallet_transactions
FOR EACH ROW EXECUTE FUNCTION update_wallet_balance();


-- 3. Split Payments Support
-- We need a way to support multiple methods for a SINGLE payment record, OR split the payment record itself.
-- OPTION A: Master Payment + Payment Methods
-- OPTION B: Allow "payments" table to have entries that sum up to the total.

-- We treat 'payments' table as the DEBT/CHARGE generated by an appointment.
-- And 'payment_transactions' as the ACTUAL MONEY received.

CREATE TABLE IF NOT EXISTS public.payment_transactions (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    payment_id UUID REFERENCES public.payments(id) NOT NULL,
    amount DECIMAL(10, 2) NOT NULL,
    method TEXT NOT NULL CHECK (method IN ('cash', 'card', 'transfer', 'wallet')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    notes TEXT,
    clinic_id UUID REFERENCES public.clinics(id)
    -- created_by linked via RLS/Auth
);

-- Trigger to update parent 'payments' status (fully paid vs partial)
CREATE OR REPLACE FUNCTION update_payment_status()
RETURNS TRIGGER AS $$
DECLARE
    v_total_paid DECIMAL(10, 2);
    v_total_amount DECIMAL(10, 2);
BEGIN
    SELECT amount INTO v_total_amount FROM payments WHERE id = NEW.payment_id;
    
    SELECT COALESCE(SUM(amount), 0) INTO v_total_paid 
    FROM payment_transactions 
    WHERE payment_id = NEW.payment_id;

    -- Update parent payment record with amount paid so far
    UPDATE payments 
    SET amount_paid = v_total_paid,
        status = CASE WHEN v_total_paid >= v_total_amount THEN 'completed' ELSE 'partial' END
    WHERE id = NEW.payment_id;
    
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS check_payment_completion ON payment_transactions;
CREATE TRIGGER check_payment_completion
AFTER INSERT ON payment_transactions
FOR EACH ROW EXECUTE FUNCTION update_payment_status();

-- Add 'amount_paid' tracking column to payments if not exists
DO $$ 
BEGIN 
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'payments' AND column_name = 'amount_paid') THEN 
        ALTER TABLE public.payments ADD COLUMN amount_paid DECIMAL(10, 2) DEFAULT 0; 
    END IF; 
END $$;


-- 4. Cash Basis Commissions
-- Modify commission logic to calculate based on payment_transactions, NOT appointment completion.

ALTER TABLE public.doctor_commissions 
ADD COLUMN IF NOT EXISTS source_transaction_id UUID REFERENCES public.payment_transactions(id);

-- Trigger on payment_transactions to generate commission
CREATE OR REPLACE FUNCTION handle_commission_on_transaction()
RETURNS TRIGGER AS $$
DECLARE
    v_appointment_id UUID;
    v_doctor_id UUID;
    v_commission_pct DECIMAL(5, 2);
    v_commission_amt DECIMAL(10, 2);
    v_clinic_id UUID;
BEGIN
    -- Get appointment info via payment
    SELECT appointment_id, clinic_id INTO v_appointment_id, v_clinic_id FROM payments WHERE id = NEW.payment_id;
    
    IF v_appointment_id IS NOT NULL THEN
        SELECT doctor_id INTO v_doctor_id FROM appointments WHERE id = v_appointment_id;

        IF v_doctor_id IS NOT NULL THEN
            -- Simply apply global percentage for now (refining logic to be robust like before)
            -- Note: In real scenarios we might want to check treatment specific commission again, but global is safer default
            SELECT percentage INTO v_commission_pct FROM commission_settings WHERE doctor_id = v_doctor_id;
            
            IF FOUND AND v_commission_pct > 0 THEN
                v_commission_amt := (NEW.amount * v_commission_pct) / 100;
                
                INSERT INTO doctor_commissions (
                    doctor_id, 
                    appointment_id, 
                    amount, 
                    status, 
                    created_at, 
                    clinic_id,
                    source_transaction_id
                ) VALUES (
                    v_doctor_id,
                    v_appointment_id,
                    v_commission_amt,
                    'pending', -- Pending payout to doctor
                    NOW(),
                    v_clinic_id,
                    NEW.id
                );
            END IF;
        END IF;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS generate_commission_on_pay ON payment_transactions;
CREATE TRIGGER generate_commission_on_pay
AFTER INSERT ON payment_transactions
FOR EACH ROW EXECUTE FUNCTION handle_commission_on_transaction();

-- DISABLE old commission trigger from Phase 1
-- We replace the function 'handle_appointment_completion' with a new one that ONLY generates debt (payment record)
-- and does NOT generate commission.

CREATE OR REPLACE FUNCTION handle_appointment_completion_debt_only()
RETURNS TRIGGER AS $$
DECLARE
    v_treatment_price DECIMAL(10, 2) := 0;
    v_treatment_record RECORD;
BEGIN
    -- Only proceed if status changed to 'completed'
    IF NEW.status = 'completed' AND (OLD.status IS DISTINCT FROM 'completed') THEN
        
        -- 1. Get Treatment details and Price
        -- Try to match by treatment_type (UUID) first
        IF NEW.treatment_type IS NOT NULL THEN
             SELECT * INTO v_treatment_record FROM treatments WHERE id = NEW.treatment_type;
        END IF;

        -- If found, set price. If not found (or treatment_type null), try fallback by title
        IF v_treatment_record.id IS NOT NULL THEN
            v_treatment_price := COALESCE(v_treatment_record.base_price, 0);
        ELSE
            -- Frontend fallback logic matches by title. We replicate this but it's fragile.
            SELECT * INTO v_treatment_record FROM treatments WHERE name = NEW.title LIMIT 1;
            IF FOUND THEN
                v_treatment_price := COALESCE(v_treatment_record.base_price, 0);
            END IF;
        END IF;

        -- 2. Create Payment Record (Pending Collection / Debt)
        -- Check if specific payment for this appointment already exists to avoid duplicates
        IF NOT EXISTS (SELECT 1 FROM payments WHERE appointment_id = NEW.id) THEN
            INSERT INTO payments (
                appointment_id,
                amount,
                status, -- 'pending' means debt exists but not paid
                patient_id,
                created_at,
                description
                -- clinic_id auto-set by trigger
            ) VALUES (
                NEW.id,
                v_treatment_price,
                'pending',
                NEW.patient_id,
                NOW(),
                'Consulta / Tratamiento: ' || COALESCE(v_treatment_record.name, NEW.title)
            );
        END IF;

        -- NO COMMISSION LOGIC HERE because it's now handled by payment_transactions trigger
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Rebind trigger to new function
DROP TRIGGER IF EXISTS on_appointment_complete ON appointments;
CREATE TRIGGER on_appointment_complete
AFTER UPDATE OF status ON appointments
FOR EACH ROW
EXECUTE FUNCTION handle_appointment_completion_debt_only();
